#MAGIAVVENTURE_LIB_JWT_SECRET - MAGIAVVENTURE_LIB_JWT_VALIDITY - MAGIAVVENTURE_LIB_JWT_HEADER
#SPRING_DATA_MONGODB_URI - SPRING_DATA_MONGODB_UUID-REPRESENTATION - SPRING_DATA_MONGODB_AUTO-INDEX-CREATION

logging:
  level:
    it.magiavventure: debug